"""empty message

Revision ID: f2b227121464
Revises: f1553f3bee19
Create Date: 2019-04-26 01:33:57.621401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b227121464'
down_revision = 'f1553f3bee19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('contact', sa.String(length=128), nullable=True))
    op.add_column('post', sa.Column('uname', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_post_uname'), 'post', ['uname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_uname'), table_name='post')
    op.drop_column('post', 'uname')
    op.drop_column('post', 'contact')
    # ### end Alembic commands ###
